contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wgsnano channel"
    url: https://nfcore.slack.com/channels/wgsnano
    about: Discussion about the nf-core/wgsnano pipeline
